version: '{build}'

image: Visual Studio 2013

# called before clone
init:
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - echo %Configuration%

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

# Note mkdir is from Git (C:\Program Files\Git\usr\bin\mkdir.exe)
# It might give unexpected results (use md instead)call create-files.cmd
before_build:
  - call C:\Qt\5.5\msvc2013_64\bin\qtenv2.bat
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo curl -L -O https://github.com/i-RIC/iricdev/archive/master.zip
  - curl -L -O https://github.com/i-RIC/iricdev/archive/master.zip
  - 7z x master.zip
  - cd iricdev-master
  - md lib
  - cd lib
  - echo curl -L -o install.zip "https://ci.appveyor.com/api/projects/i-RIC/iricdev/artifacts/lib/install.zip?branch=master&job=Configuration%3A+%Configuration%"
  - curl -L -o install.zip "https://ci.appveyor.com/api/projects/i-RIC/iricdev/artifacts/lib/install.zip?branch=master&job=Configuration%3A+%Configuration%"
  - md install
  - cd install
  - 7z x ..\install.zip
  - cd %APPVEYOR_BUILD_FOLDER%\iricdev-master
  - call create-files.cmd
  - cd %APPVEYOR_BUILD_FOLDER%
  - if not exist libdlls (md libdlls)
  - if not exist libdlls\Debug (md libdlls\Debug)
  - if not exist libdlls\Release (md libdlls\Release)
  - copy /y .\iricdev-master\paths.pri .
  - copy /y .\iricdev-master\dirExt.prop .\tools\data\.
  - qmake -recursive -tp vc

# build using cmake tools
build_script:
  - msbuild /nologo /verbosity:minimal /p:Configuration=%Configuration% src.sln
